### ISSUE TITLE
Add additional restrictions on pattern properties 

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#20]
Currently in RAML 1.0 RC1, it is fully valid to declare a pattern property whose regex will match on an existing property name. For example:

``` yaml
Person:
  properties:
    a: string
   [a] : number
```

This definition is illegal because property with name 'a' will be matched both to normal property and to a pattern property. RC2 should clearly state that this situations are not valid to avoid these conflicts.
