### ISSUE TITLE
Clarify that 'discriminator' and 'discriminatorValue' can only be defined for global type definitions

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#21]
Due to its nature, RC2 should explicitly state that defining `discriminator` and `discriminatorValue` should only be available for global type definitions and not for any types that are declared inline.

``` yaml
# valid
types:
   Device:
     type: Phone | Notebook
     discriminator: kind
```

``` yaml
# invalid
application/json: 
   type: Phone | Notebook
   discriminator: kind
```
