### ISSUE TITLE
Suggestion to change how you define multiple examples

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#45]
In the current RAML RC1 you can define multiple examples either using an array of `-content` keys or unique names followed by `content`. Both options are illustrated below:

``` yaml
types:
  Org:
    type: object
    properties:
      name: string
      address?: string
    examples: # multiple examples using an array of different contents
      - content:
          name: Acme
      - content:
          name: Software Corp
          address: 35 Central Street
```

``` yaml
types:
  Org:
    type: object
    properties:
      name: string
      address?: string
    examples: # multiple examples identified by their unique key names
      acme:
        content:
          name: Acme
      softwareCorp:
        content:
          name: Software Corp
          address: 35 Central Street
```

The first example using an array of `-content` keys is not valid according to YAML and should not be supported in the spec IMHO. The second uses unique keys which is fine, but we should remove `content` as it is not coherent to how you define a single example like the following:

``` yaml
types:
  Org:
    type: object
    properties:
      name: string
      address?: string
    example: # single example
      name: Software Corp
      address: 35 Central Street
```

My suggestion would be to use the same set of properties available in a single example also in examples except that each example needs to be identified by a unique key. The following is a modified version illustrates that:

``` yaml
types:
  Org:
    type: object
    properties:
      name: string
      address?: string
    examples: # multiple examples identified by their unique key names
      - acme:
          name: Acme
      - softwareCorp:
          name: Software Corp
          address: 35 Central Street
```

I am looking forward to hear some feedback.
