### ISSUE TITLE
Allow '/' in URI parameters - support level 2 URI templates

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#68]
The spec says:

>  The baseUri property's value MUST conform to the URI specification [RFC2396] or a Level 1 Template URI as defined in RFC 6570 [RFC6570].

In order to be able to document more versatile APIs, _Level 2_ templates should also be allowed, but only if the macro is the last piece in the URL

Example:

``` yaml
#%RAML 0.8
title: My Sample API
/files{+path}:
  uriParameters:
    path:
      description: The full path to the desired file
      type: string
      example: /my/file
```
